version: "3"

services:
  postgres:
    image: postgres:latest
    # todo: remove the host-network-ed port
    ports:
      - 5432:5432
    # networks:
    # - internal
    # volumes:
    #   - vol-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 60
#   pgmigrate:
#     image: 

#   service-jwt:
#     image:
#       build: .