version: "3"

networks:
  internal:

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
    - 5432:5432
    networks:
    - internal
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 60
  pgmigrate:
    image: ghcr.io/peterldowns/pgmigrate:latest
    command: pgmigrate migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
    - internal
    volumes:
    - ./migrations:/migrations
    environment:
      PGM_MIGRATIONS: /migrations
      PGM_DATABASE: ${PG_URL}
  smtp:
    image: rnwood/smtp4dev
    restart: unless-stopped
    networks:
    - internal
    ports:
    - 8001:80
    - "2525:25"
  jwt-service:
    build: .
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
    - internal
    ports:
    - 8000:8080
    env_file: ".env"
    environment:
      PG_URL: ${PG_URL}
